### ISSUE TITLE
Request: Sanitize

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [kgar/foundry-vtt-more-handlebars-helpers#3]
**Helper**
[{{sanitize}}](https://github.com/helpers/handlebars-helpers/blob/master/lib/html.js#L121)
Strip HTML tags from a string, so that only the text nodes are preserved.

Params
str {String}: The string of HTML to sanitize.
returns {String}
Example

{{sanitize "<span>foo</span>"}}

**Code**
```
/**
 * Strip HTML tags from a string, so that only the text nodes
 * are preserved.
 *
 * ```handlebars
 * {{sanitize "<span>foo</span>"}}
 * <!-- results in: 'foo' -->
 * ```
 *
 * @param {String} `str` The string of HTML to sanitize.
 * @return {String}
 * @api public
 */

helpers.sanitize = function(str) {
  return html.sanitize(str);
};
```

**Comment by kgar** [comment]
This will release in 1.1.0 (very soon).

I am using the same implementation that is used by the big Handlebars Helpers library, which is the JavaScript/TypeScript implementation of `striptags`: https://github.com/ericnorris/striptags

**Comment by ObsidianTTRPGProject** [comment]
Thank you :)

**Comment by kgar** [comment]
Reopening. I meant to allow you to close these issues when you had a chance to test out the new helpers. v1.1.0 is ready.

**Comment by ObsidianTTRPGProject** [comment]
Thank you. This works amazingly!
