### ISSUE TITLE
RegExp helper please

### ISSUE THREAD

**Issue by farling42** [kgar/foundry-vtt-more-handlebars-helpers#6]
A user wants to strip out blank lines, but that requires a RegExp to be used.

A simple handler such as:

```
function hb_regexp(text) {
    return new RegExp(text, "g");
}

Handlebars.registerHelper('hb-regexp', hb_regexp);
```

This will allow a user to use an expression to remove break lines from the HTML of item/actor descriptions, such as:

```
{{{more-handlebars-helpers-sanitize (more-handlebars-helpers-replaceAll system.description.value (more-handlebars-helpers-regexp '\n<hr />') '') }}}
```

(The "\n" isn't recognised by the basic replaceAll function)

**Comment by kgar** [comment]
You got it! This is a really cool orthogonal helper to put in.

Would you like the flag to be optional with a default to "g"? Asking on behalf of the "i" flag.

**Comment by kgar** [comment]
I ran a test with this helper, and here's what I'm seeing:

The helper:
```
export default function (text) {
  return new RegExp(text, 'g');
}
```

```js
Handlebars.compile(`{{ more-handlebars-helpers-sanitize (more-handlebars-helpers-replaceAll (more-handlebars-helpers-regexp value '\n<hr />') ' ') }}`)({ value: "Hello,\n<hr />there,\n<hr />world!"})
```

Result:
```
'/Hello,\\n&lt;hr \\/&gt;there,\\n&lt;hr \\/&gt;world!/g'
```

I'll keep digging to see why it's not working like we'd expect. If you see something in my test code above I could do differently, let me know.

**Comment by kgar** [comment]
Putting my bad test here in the public helped me fix my bad test 🤣

Updated test:
```js
Handlebars.compile(`{{ more-handlebars-helpers-sanitize (more-handlebars-helpers-replaceAll value (more-handlebars-helpers-regexp '\n<hr />') ' ') }}`)({ value: "Hello,\n<hr />there,\n<hr />world!"})
```

Result:
```
'Hello, there, world!'
```

🎉

**Comment by farling42** [comment]
Concerning optional, I guess the RegExp could take a second optional parameter, which would be the flags passed as the second argument for the RegExp constructor.  Much better for those who like more than just "g" :-)

**Comment by kgar** [comment]
Version 1.2.0 has released. Give it a go, and if things are working, go ahead and close the issue.

**Comment by farling42** [comment]
It is working just fine. Thanks for the rapid turn-around!

**Comment by ObsidianTTRPGProject** [comment]
Thank you both! We have rendering stat-blocks!

![image](https://github.com/kgar/foundry-vtt-more-handlebars-helpers/assets/96321415/68c01f65-f30c-4e99-8dad-a618fc8a9f64)

**Comment by farling42** [comment]
It just needs the Trigger/Effect text better formatted now 😉

**Comment by ObsidianTTRPGProject** [comment]
Baby-steps lol.
