### ISSUE TITLE
Request: Math Helpers

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [kgar/foundry-vtt-more-handlebars-helpers#8]
Would it be possible to get some basic maths helpers? I'm seeking to get basic subtraction working to automate the Multi Attack Penalty for PF2e actions. 

Doco: https://assemble.io/helpers/helpers-math.html
Source: https://github.com/helpers/handlebars-helpers/blob/master/lib/math.js

Thanks,
Josh

**Comment by kgar** [comment]
I will begin adding these, starting with subtraction. I'll get an early release out with what you need and then continue to add the rest in a subsequent release.

**Comment by kgar** [comment]
I'm wondering how we should handle the unexpected for math operators...
The source code in the link throws TypeErrors when either of the supplied values is not a number. 
Would you prefer a script fail with error when invalid input is provided? Or should it just return the original value when unable to do the math?

**Comment by ObsidianTTRPGProject** [comment]
Sorry, blew my pc up :( . Just getting back up and operational now. 

The situations where this is going to be used should technically be in the required format already I would hope. Honestly I would be happy to just return the original value when unable to do the maths. 

Have found a situation to use this one also now. 

Handlebars.registerHelper('add', function(a, b) {
  return a + b;
});

**Comment by kgar** [comment]
Oh no! Sorry to hear about your PC.
Well, I have been very busy on the Tidy 5e Sheets rewrite front, but I can take some time now to work on this.

Ok, as a general rule, I will go ahead and return whatever your original value was if it indeed is not eligible for maths.

**Comment by kgar** [comment]
Released! https://github.com/kgar/foundry-vtt-more-handlebars-helpers/releases/tag/v1.3.0

Have a look, and let me know if any adjustments are needed. Otherwise, feel free to close the issue.

**Comment by ObsidianTTRPGProject** [comment]
Thank you so much!
